- name: Create kubeadm config file
  template:
    dest: /etc/kubeadm.yml
    src: "{{ kubeadm_template }}"
    mode: 0600

- name: Kubeadm list images
  shell: 'kubeadm config images list --config /etc/kubeadm.yml'
  register: images_list

- name: Pull images
  raw: |
    if [[ {{ item }} =~ "etcd" ]]; then
      crictl pull public.ecr.aws/eks-distro/etcd-io/etcd:v3.4.15-eks-1-20-1
    elif [[ {{ item }} =~ "coredns" ]]; then
      crictl pull public.ecr.aws/eks-distro/coredns/coredns:v1.8.3-eks-1-20-1
    else
      crictl pull {{ item }}
    fi
  loop: "{{ images_list.stdout_lines }}"  

- name: Pull additional images
  command: "crictl pull {{ item }}"
  loop:
    - docker.io/calico/cni:v3.20.1
    - docker.io/calico/pod2daemon-flexvol:v3.20.1
    - docker.io/calico/node:v3.20.1
    - docker.io/calico/kube-controllers:v3.20.1
    - public.ecr.aws/isovalent/cilium:v1.9.10-eksa.1
    - public.ecr.aws/isovalent/operator-generic:v1.9.10-eksa.1

- name: Delete kubeadm config
  file:
    path: /etc/kubeadm.yml
    state: absent
  when: ansible_os_family != "Flatcar"
